### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RS2007** [RS2007/CHIP-8_Emulator#1]
- [ ] Assembly instructions incorrect in some places fix them
- [ ] Detailed documentation(specially highlighting the bitwise operations)
- [ ] Loading the font in initChip
- [ ] CLI Interface to load roms
